[package]
name = "trex"
version = "0.1.0"
edition = "2021"
authors = ["Francis Fortier <francis.fortier@gmail.com>"]

[dependencies]
trex-parser = { path = "../parser" }
clap = { version ="4.4.7", features = ["derive"] }
termion = "2.0.1"
